# Generated by Django 6.0.3 on 2026-03-27 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kebabarna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200)),
                ('adresa', models.CharField(max_length=255)),
                ('mesto', models.CharField(max_length=100)),
                ('oteviraci_doba', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('typ_masa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recenze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hodnoceni_celkove', models.IntegerField()),
                ('hodnoceni_maso', models.IntegerField()),
                ('komentar', models.TextField()),
                ('datum_vytvoreni', models.DateTimeField(auto_now_add=True)),
                ('kebabarna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kebabarna')),
            ],
        ),
        migrations.CreateModel(
            name='Fotografie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_odkaz', models.URLField(max_length=500)),
                ('recenze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotky', to='app.recenze')),
            ],
        ),
        migrations.CreateModel(
            name='Uzivatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100)),
                ('heslo_hash', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('oblibena_kebabarna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stali_zakaznici', to='app.kebabarna')),
            ],
        ),
        migrations.AddField(
            model_name='recenze',
            name='uzivatel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.uzivatel'),
        ),
    ]
