# Generated by Django 6.0.3 on 2026-03-27 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KebabShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('opening_hours', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('meat_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='uzivatel',
            name='oblibena_kebabarna',
        ),
        migrations.AlterField(
            model_name='recenze',
            name='kebabarna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kebabshop'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('favorite_kebab_shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stali_zakaznici', to='app.kebabshop')),
            ],
        ),
        migrations.AlterField(
            model_name='recenze',
            name='uzivatel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
        migrations.DeleteModel(
            name='Kebabarna',
        ),
        migrations.DeleteModel(
            name='Uzivatel',
        ),
    ]
